### ISSUE TITLE
Inconsistent use of tabs and spaces in deeplab_Resnet.py at many places.

### ISSUE THREAD

**Issue by prabhant** [val-iisc/GD-UAP#1]
after running the evaluation code 
"python3 get_outputs.py --network dl_vgg16 --adv_im perturbations
/dl_vgg_with_data.npy --im_list utils/pascal_test.txt --save_path output/ --gpu 0 
Traceback (most recent call last):
  File "get_outputs.py", line 3, in <module>
    from nets.deeplab_resnet import Res_Deeplab
  File "/home/prabhant/Uniwork/spring-18/KittiSeg/ATTACKS/GD-UAP/segmentation/nets/deeplab_resnet.py", line 60
    for i in self.bn1.parameters():
                                  ^
TabError: inconsistent use of tabs and spaces in indentation
"

Though i could've corrected one error but this error occured many times in the entire file. Please correct it.

**Comment by BardOfCodes** [comment]
Hey Prabhant!
Thank you for pointing out this error. I have formatted the entire repository to follow pep-8 style guide. It should have taken care of poor usage of tabs and spaces as well. 
In future, you can consider usage of autopep8 for formatting such files, in case you face this issue!
